title: Aakash Raman
# LinkedIn profile picture - Update this URL when your LinkedIn profile picture changes
# To get the current URL: Right-click your LinkedIn profile picture > Copy image address
logo: https://media.licdn.com/dms/image/v2/D4E03AQFMn02lA1B5fQ/profile-displayphoto-scale_400_400/B4EZrax0h_IoAg-/0/1764607086039?e=1771459200&v=beta&t=oRBGJAQpY8R394gLX8lw20h-HIPyHjr-PJaafetPipk
# Fallback to local image if LinkedIn URL fails
linkedin_profile: https://www.linkedin.com/in/aakash-raman-66676b38/
linkedin_username: aakash-raman-66676b38
email: aakashr93@gmail.com
description: Detection Engineer | Threat Hunter & DFIR Practitioner | Aspiring Purple Teamer
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Since we have the theme files locally, we use the theme directly
# No remote_theme needed as all files are in the repository

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house" aria-hidden="true"></i>
    link: /
  - name: Projects
    icon: <i class="fa-solid fa-code" aria-hidden="true"></i>
    link: /projects
  - name: Contact
    icon: <i class="fa-solid fa-envelope" aria-hidden="true"></i>
    link: /contact
  - name: Resume
    icon: <svg xmlns="https://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: /assets/img/Aakash_Nov_Resume.pdf
  - name: CV
    icon: <svg xmlns="https://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 512 512"><path fill="currentColor" d="M249.18 328.324c-9.788 15.384-19.179 30.434-40.222 45.055c-11.256 7.89-37.164 23.306-73.99 23.306C64.709 396.685 8 345.605 8 255.801c0-78.486 53.345-140.486 128.466-140.486c30.434 0 57.474 10.521 77.387 26.304c18.414 14.65 27.038 29.304 34.563 42.456l-52.58 26.273c-3.762-8.626-8.29-17.649-19.913-27.406c-12.784-10.155-25.54-13.152-36.46-13.152c-42.821 0-65.364 39.825-65.364 84.145c0 58.238 29.7 87.143 65.364 87.143c34.563 0 48.48-24.042 57.474-39.426zm184.194-204.75H504l-92.037 265.22h-67.597l-90.904-265.22h70.625l54.843 188.6z"/></svg>
    link: /assets/img/Aakash_September_CV.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github" aria-hidden="true"></i>
    link: https://github.com/aakashraman
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin" aria-hidden="true"></i>
    link: https://www.linkedin.com/in/aakash-raman-66676b38/
  - name: Blogs
    icon: <i class="fa-solid fa-pen" aria-hidden="true"></i>
    link: https://medium.com/@araman99

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
